server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: register-service
          uri: lb://register-service/
          predicates:
            - Path=/api/account/register
        - id: login-service
          uri: lb://login-service/
          predicates:
            - Path=/api/account/login